[[mods]]
name = "3D Skin Layers"
file = "mods/3dskinlayers.pw.toml"

[[mods]]
name = "[EMF] Entity Model Features"
file = "mods/entity-model-features.pw.toml"

[[mods.dependencies]]
name = "[ETF] Entity Texture Features"
file = "mods/entitytexturefeatures.pw.toml"

[[mods]]
name = "[ESF] Entity Sound Features"
file = "mods/esf.pw.toml"

[[mods.dependencies]]
name = "[EMF] Entity Model Features"
file = "mods/entity-model-features.pw.toml"

[[mods.dependencies.dependencies]]
name = "[ETF] Entity Texture Features"
file = "mods/entitytexturefeatures.pw.toml"

[[mods.dependencies]]
name = "[ETF] Entity Texture Features"
file = "mods/entitytexturefeatures.pw.toml"

[[mods]]
name = "[ETF] Entity Texture Features"
file = "mods/entitytexturefeatures.pw.toml"

[[mods]]
name = "Euphoria Patches"
file = "mods/euphoria-patches.pw.toml"

[[mods]]
name = "Fusion (Connected Textures)"
file = "mods/fusion-connected-textures.pw.toml"

[[mods]]
name = "Iris Shaders"
file = "mods/iris.pw.toml"

[[mods.dependencies]]
name = "Sodium"
file = "mods/sodium.pw.toml"

[[mods]]
name = "Sodium"
file = "mods/sodium.pw.toml"

[[mods]]
name = "Sodium Dynamic Lights"
file = "mods/sodium-dynamic-lights.pw.toml"

[[mods.dependencies]]
name = "Sodium Options API"
file = "mods/sodium-options-api.pw.toml"

[[mods.dependencies.dependencies]]
name = "Sodium"
file = "mods/sodium.pw.toml"

[[mods.dependencies]]
name = "Sodium"
file = "mods/sodium.pw.toml"

[[mods]]
name = "Sodium Extras"
file = "mods/sodium-extras.pw.toml"

[[mods.dependencies]]
name = "Sodium Options API"
file = "mods/sodium-options-api.pw.toml"

[[mods.dependencies.dependencies]]
name = "Sodium"
file = "mods/sodium.pw.toml"

[[mods.dependencies]]
name = "Sodium"
file = "mods/sodium.pw.toml"

[[mods]]
name = "Sodium Options Mod Compat"
file = "mods/sodium-options-mod-compat.pw.toml"

[[mods.dependencies]]
name = "Sodium Options API"
file = "mods/sodium-options-api.pw.toml"

[[mods.dependencies.dependencies]]
name = "Sodium"
file = "mods/sodium.pw.toml"

[[mods]]
name = "YUNG's Menu Tweaks"
file = "mods/yungs-menu-tweaks.pw.toml"

[[mods.dependencies]]
name = "YUNG's API"
file = "mods/yungs-api.pw.toml"

[[resourcepacks]]
name = "(Bee's) Fancy Crops"
file = "resourcepacks/fancy-crops.pw.toml"

[[resourcepacks]]
name = "Fresh Animations"
file = "resourcepacks/fresh-animations.pw.toml"

[[resourcepacks]]
name = "Fresh Animations: Extensions"
file = "resourcepacks/fresh-animations-extensions.pw.toml"

[[resourcepacks.dependencies]]
name = "Fresh Animations"
file = "resourcepacks/fresh-animations.pw.toml"

[[resourcepacks]]
name = "Fresh Animations: Player Extension"
file = "resourcepacks/fa-player-extension.pw.toml"

[[resourcepacks]]
name = "Fusion 3D Items"
file = "resourcepacks/fusion-3d-items.pw.toml"

[[resourcepacks.dependencies]]
name = "Fusion (Connected Textures)"
file = "mods/fusion-connected-textures.pw.toml"

[[resourcepacks]]
name = "Fusion Block Transitions"
file = "resourcepacks/fusion-block-transitions.pw.toml"

[[resourcepacks.dependencies]]
name = "Fusion (Connected Textures)"
file = "mods/fusion-connected-textures.pw.toml"

[[resourcepacks]]
name = "Fusion Connected Blocks"
file = "resourcepacks/fusion-connected-blocks.pw.toml"

[[resourcepacks.dependencies]]
name = "Fusion (Connected Textures)"
file = "mods/fusion-connected-textures.pw.toml"

[[resourcepacks]]
name = "Fusion Connected Glass"
file = "resourcepacks/fusion-connected-glass.pw.toml"

[[resourcepacks.dependencies]]
name = "Fusion (Connected Textures)"
file = "mods/fusion-connected-textures.pw.toml"

[[resourcepacks]]
name = "Fusion Emissive Ores"
file = "resourcepacks/fusion-emissive-ores.pw.toml"

[[resourcepacks.dependencies]]
name = "Fusion (Connected Textures)"
file = "mods/fusion-connected-textures.pw.toml"

[[resourcepacks]]
name = "Fusion Stacking Items"
file = "resourcepacks/fusion-stacking-items.pw.toml"

[[resourcepacks.dependencies]]
name = "Fusion (Connected Textures)"
file = "mods/fusion-connected-textures.pw.toml"

[[resourcepacks]]
name = "Icons"
file = "resourcepacks/icons.pw.toml"

[[resourcepacks]]
name = "Mandala's GUI - Add-Ons"
file = "resourcepacks/mandalas-gui-add-ons.pw.toml"

[[resourcepacks]]
name = "Mandala's GUI - Dark mode"
file = "resourcepacks/mandalas-gui-dark-mode.pw.toml"

[[shaderpacks]]
name = "Complementary Shaders - Reimagined"
file = "shaderpacks/complementary-reimagined.pw.toml"

[[shaderpacks]]
name = "Complementary Shaders - Unbound"
file = "shaderpacks/complementary-unbound.pw.toml"
