name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "evictedcucumber-packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3ae67df0dba74aee832935d477b260a3679842220abb612028540d0ecc31758"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
