name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "evictedcucumber-packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab4c2571a6119ad4851e1495397e91aa422452f7a1acd2220488e46a06de9898"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[config-files]
neoforge = ["config/fml.toml", "config/neoforge-client.toml", "config/neoforge-common.toml", "config/neoforge-server.toml"]
pack = ["options.txt"]
