name = "Create Adventured"
author = "evictedcucumber"
version = "1.0.0"
pack-format = "evictedcucumber-packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcf5b848e0cff5010b610d2926e5e49423c0187ff772a5a48dda5c60aa489ba9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"

[config-files]
neoforge = ["config/fml.toml", "config/neoforge-client.toml", "config/neoforge-common.toml", "config/neoforge-server.toml"]
pack = ["options.txt"]
